### PR TITLE
Update README.md for installing mjml globally for Rails 7.x.x with importmaps

### PR DESCRIPTION
**Pull request by loqimean**

### CODE REVIEW

**Comment by sighmon** [comment]
@loqimean Thanks for the PR - would you mind adding some more information with links?

**Comment by loqimean** [comment]
> @loqimean Thanks for the PR - would you mind adding some more information with links?

Thanks, but I think no, that all what user need, it helps me and I hope can help others to have clear mind of installation MJML and using your gem

**Comment by loqimean** [comment]
Btw, I think that also cool idea is to add warning that user should add MJML installation to the CI

**Review by sighmon — CHANGES_REQUESTED** [review]
Would you mind moving your additions below the other npm install command so they're together?

**Comment by loqimean** [comment]
> Would you mind moving your additions below the other npm install command so they're together?

okay

**Comment by loqimean** [comment]
> Would you mind moving your additions below the other npm install command so they're together?

it is

**Review by sighmon — APPROVED** [review]
Great, thank you!

**Comment by jlxq0** [comment]
I think more information is needed for Rails 7 and import maps. How and what would you pin (or in general do) to make mcml-rails work in Rails 7?

**Comment by sighmon** [comment]
@loqimean ☝🏽Would you mind expanding on your experience?

**Comment by loqimean** [comment]
> @loqimean ☝🏽Would you mind expanding on your experience?

yes, of course

**Comment by loqimean** [comment]
> I think more information is needed for Rails 7 and import maps. How and what would you pin (or in general do) to make mjml-rails work in Rails 7?

Hi, so in a nutshell you should just install MJML as a global package without pinning or requiring, just do it), it is really simple thing)

**Comment by jlxq0** [comment]
Hm, idk. Could make it work that way for dev. But it doesn't seem to be a proper way for production environments like on heroku.

**Comment by loqimean** [comment]
> Hm, idk. Could make it work that way for dev. But it doesn't seem to be a proper way for production environments like on heroku.

hm, for VPS all is good, I'd check it yesterday btw, but what about Heroku.., hm, I think the following link can help you with it for Heroku service:
https://stackoverflow.com/a/33019204/17425539

**Pull request merged**
